//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt_na_generaciyu
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Персонал.
    /// </summary>
    // *** Start programmer edit section *** (Персонал CustomAttributes)

    // *** End programmer edit section *** (Персонал CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПерсоналE", new string[] {
            "ФИО as \'ФИО\'",
            "Телефон as \'Телефон\'",
            "Должность as \'Должность\'",
            "Должность.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Должность.Наименование"})]
    [MasterViewDefineAttribute("ПерсоналE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ПерсоналL", new string[] {
            "ФИО as \'ФИО\'",
            "Телефон as \'Телефон\'",
            "Должность.Наименование as \'Наименование\'"})]
    public class Персонал : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private int fТелефон;
        
        private IIS.Proekt_na_generaciyu.Должность fДолжность;
        
        // *** Start programmer edit section *** (Персонал CustomMembers)

        // *** End programmer edit section *** (Персонал CustomMembers)

        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Персонал.Телефон CustomAttributes)

        // *** End programmer edit section *** (Персонал.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Персонал.Телефон Get start)

                // *** End programmer edit section *** (Персонал.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Персонал.Телефон Get end)

                // *** End programmer edit section *** (Персонал.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Персонал.Телефон Set start)

                // *** End programmer edit section *** (Персонал.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Персонал.Телефон Set end)

                // *** End programmer edit section *** (Персонал.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Персонал.ФИО CustomAttributes)

        // *** End programmer edit section *** (Персонал.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Персонал.ФИО Get start)

                // *** End programmer edit section *** (Персонал.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Персонал.ФИО Get end)

                // *** End programmer edit section *** (Персонал.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Персонал.ФИО Set start)

                // *** End programmer edit section *** (Персонал.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Персонал.ФИО Set end)

                // *** End programmer edit section *** (Персонал.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Персонал.
        /// </summary>
        // *** Start programmer edit section *** (Персонал.Должность CustomAttributes)

        // *** End programmer edit section *** (Персонал.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.Proekt_na_generaciyu.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (Персонал.Должность Get start)

                // *** End programmer edit section *** (Персонал.Должность Get start)
                IIS.Proekt_na_generaciyu.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (Персонал.Должность Get end)

                // *** End programmer edit section *** (Персонал.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Персонал.Должность Set start)

                // *** End programmer edit section *** (Персонал.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Персонал.Должность Set end)

                // *** End programmer edit section *** (Персонал.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПерсоналE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПерсоналE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПерсоналE", typeof(IIS.Proekt_na_generaciyu.Персонал));
                }
            }
            
            /// <summary>
            /// "ПерсоналL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПерсоналL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПерсоналL", typeof(IIS.Proekt_na_generaciyu.Персонал));
                }
            }
        }
    }
}
