//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt_na_generaciyu
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Целевая аудит.
    /// </summary>
    // *** Start programmer edit section *** (ЦелеваяАудит CustomAttributes)

    // *** End programmer edit section *** (ЦелеваяАудит CustomAttributes)
    [AutoAltered()]
    [Caption("Целевая аудит")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЦелеваяАудитE", new string[] {
            "Пол as \'Пол\'",
            "Национальн as \'Национальн\'",
            "Возраст as \'Возраст\'",
            "СемейнПол as \'Семейн пол\'",
            "Образование as \'Образование\'",
            "ДатаРожд as \'Дата рожд\'",
            "ФИО as \'ФИО\'"})]
    [View("ЦелеваяАудитL", new string[] {
            "Пол as \'Пол\'",
            "Национальн as \'Национальн\'",
            "Возраст as \'Возраст\'",
            "СемейнПол as \'Семейн пол\'",
            "Образование as \'Образование\'",
            "ДатаРожд as \'Дата рожд\'",
            "ФИО as \'ФИО\'"})]
    public class ЦелеваяАудит : ICSSoft.STORMNET.DataObject
    {
        
        private string fПол;
        
        private string fНациональн;
        
        private int fВозраст;
        
        private string fСемейнПол;
        
        private string fОбразование;
        
        private string fДатаРожд;
        
        private string fФИО;
        
        // *** Start programmer edit section *** (ЦелеваяАудит CustomMembers)

        // *** End programmer edit section *** (ЦелеваяАудит CustomMembers)

        
        /// <summary>
        /// Возраст.
        /// </summary>
        // *** Start programmer edit section *** (ЦелеваяАудит.Возраст CustomAttributes)

        // *** End programmer edit section *** (ЦелеваяАудит.Возраст CustomAttributes)
        public virtual int Возраст
        {
            get
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.Возраст Get start)

                // *** End programmer edit section *** (ЦелеваяАудит.Возраст Get start)
                int result = this.fВозраст;
                // *** Start programmer edit section *** (ЦелеваяАудит.Возраст Get end)

                // *** End programmer edit section *** (ЦелеваяАудит.Возраст Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.Возраст Set start)

                // *** End programmer edit section *** (ЦелеваяАудит.Возраст Set start)
                this.fВозраст = value;
                // *** Start programmer edit section *** (ЦелеваяАудит.Возраст Set end)

                // *** End programmer edit section *** (ЦелеваяАудит.Возраст Set end)
            }
        }
        
        /// <summary>
        /// ДатаРожд.
        /// </summary>
        // *** Start programmer edit section *** (ЦелеваяАудит.ДатаРожд CustomAttributes)

        // *** End programmer edit section *** (ЦелеваяАудит.ДатаРожд CustomAttributes)
        [StrLen(255)]
        public virtual string ДатаРожд
        {
            get
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.ДатаРожд Get start)

                // *** End programmer edit section *** (ЦелеваяАудит.ДатаРожд Get start)
                string result = this.fДатаРожд;
                // *** Start programmer edit section *** (ЦелеваяАудит.ДатаРожд Get end)

                // *** End programmer edit section *** (ЦелеваяАудит.ДатаРожд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.ДатаРожд Set start)

                // *** End programmer edit section *** (ЦелеваяАудит.ДатаРожд Set start)
                this.fДатаРожд = value;
                // *** Start programmer edit section *** (ЦелеваяАудит.ДатаРожд Set end)

                // *** End programmer edit section *** (ЦелеваяАудит.ДатаРожд Set end)
            }
        }
        
        /// <summary>
        /// Национальн.
        /// </summary>
        // *** Start programmer edit section *** (ЦелеваяАудит.Национальн CustomAttributes)

        // *** End programmer edit section *** (ЦелеваяАудит.Национальн CustomAttributes)
        [StrLen(255)]
        public virtual string Национальн
        {
            get
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.Национальн Get start)

                // *** End programmer edit section *** (ЦелеваяАудит.Национальн Get start)
                string result = this.fНациональн;
                // *** Start programmer edit section *** (ЦелеваяАудит.Национальн Get end)

                // *** End programmer edit section *** (ЦелеваяАудит.Национальн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.Национальн Set start)

                // *** End programmer edit section *** (ЦелеваяАудит.Национальн Set start)
                this.fНациональн = value;
                // *** Start programmer edit section *** (ЦелеваяАудит.Национальн Set end)

                // *** End programmer edit section *** (ЦелеваяАудит.Национальн Set end)
            }
        }
        
        /// <summary>
        /// Образование.
        /// </summary>
        // *** Start programmer edit section *** (ЦелеваяАудит.Образование CustomAttributes)

        // *** End programmer edit section *** (ЦелеваяАудит.Образование CustomAttributes)
        [StrLen(255)]
        public virtual string Образование
        {
            get
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.Образование Get start)

                // *** End programmer edit section *** (ЦелеваяАудит.Образование Get start)
                string result = this.fОбразование;
                // *** Start programmer edit section *** (ЦелеваяАудит.Образование Get end)

                // *** End programmer edit section *** (ЦелеваяАудит.Образование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.Образование Set start)

                // *** End programmer edit section *** (ЦелеваяАудит.Образование Set start)
                this.fОбразование = value;
                // *** Start programmer edit section *** (ЦелеваяАудит.Образование Set end)

                // *** End programmer edit section *** (ЦелеваяАудит.Образование Set end)
            }
        }
        
        /// <summary>
        /// Пол.
        /// </summary>
        // *** Start programmer edit section *** (ЦелеваяАудит.Пол CustomAttributes)

        // *** End programmer edit section *** (ЦелеваяАудит.Пол CustomAttributes)
        [StrLen(255)]
        public virtual string Пол
        {
            get
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.Пол Get start)

                // *** End programmer edit section *** (ЦелеваяАудит.Пол Get start)
                string result = this.fПол;
                // *** Start programmer edit section *** (ЦелеваяАудит.Пол Get end)

                // *** End programmer edit section *** (ЦелеваяАудит.Пол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.Пол Set start)

                // *** End programmer edit section *** (ЦелеваяАудит.Пол Set start)
                this.fПол = value;
                // *** Start programmer edit section *** (ЦелеваяАудит.Пол Set end)

                // *** End programmer edit section *** (ЦелеваяАудит.Пол Set end)
            }
        }
        
        /// <summary>
        /// СемейнПол.
        /// </summary>
        // *** Start programmer edit section *** (ЦелеваяАудит.СемейнПол CustomAttributes)

        // *** End programmer edit section *** (ЦелеваяАудит.СемейнПол CustomAttributes)
        [StrLen(255)]
        public virtual string СемейнПол
        {
            get
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.СемейнПол Get start)

                // *** End programmer edit section *** (ЦелеваяАудит.СемейнПол Get start)
                string result = this.fСемейнПол;
                // *** Start programmer edit section *** (ЦелеваяАудит.СемейнПол Get end)

                // *** End programmer edit section *** (ЦелеваяАудит.СемейнПол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.СемейнПол Set start)

                // *** End programmer edit section *** (ЦелеваяАудит.СемейнПол Set start)
                this.fСемейнПол = value;
                // *** Start programmer edit section *** (ЦелеваяАудит.СемейнПол Set end)

                // *** End programmer edit section *** (ЦелеваяАудит.СемейнПол Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (ЦелеваяАудит.ФИО CustomAttributes)

        // *** End programmer edit section *** (ЦелеваяАудит.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.ФИО Get start)

                // *** End programmer edit section *** (ЦелеваяАудит.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (ЦелеваяАудит.ФИО Get end)

                // *** End programmer edit section *** (ЦелеваяАудит.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦелеваяАудит.ФИО Set start)

                // *** End programmer edit section *** (ЦелеваяАудит.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (ЦелеваяАудит.ФИО Set end)

                // *** End programmer edit section *** (ЦелеваяАудит.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЦелеваяАудитE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЦелеваяАудитE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЦелеваяАудитE", typeof(IIS.Proekt_na_generaciyu.ЦелеваяАудит));
                }
            }
            
            /// <summary>
            /// "ЦелеваяАудитL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЦелеваяАудитL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЦелеваяАудитL", typeof(IIS.Proekt_na_generaciyu.ЦелеваяАудит));
                }
            }
        }
    }
}
